import { IPO, IPOStatus, IPOSector } from './types';

export const IPOS: IPO[] = [
  {
    id: 1,
    companyName: { en: 'Ecogreen Energy Holding Inc.', tr: 'Ecogreen Enerji Holding A.Ş.' },
    ticker: 'ECOGR',
    logoUrl: 'https://picsum.photos/seed/ecogr/200',
    description: { en: 'An energy company focused on renewable and sustainable solutions.', tr: 'Yenilenebilir ve sürdürülebilir çözümlere odaklanmış bir enerji şirketi.' },
    ipoDate: '2025-10-22',
    status: IPOStatus.UPCOMING,
    priceRange: [10.40, 10.40],
    finalPrice: null,
    sharesOffered: 110000000,
    exchange: 'Ana Pazar',
    sector: IPOSector.ENERGY,
    distributionMethod: { en: 'Equal Distribution', tr: 'Eşit Dağıtım' },
    background: { en: 'Ecogreen Energy Holding Inc. is a leading company in the renewable energy sector, specializing in the development and operation of solar, wind, and hydroelectric power plants.', tr: 'Ecogreen Enerji Holding A.Ş., yenilenebilir enerji sektöründe lider bir şirkettir ve güneş, rüzgar ve hidroelektrik santrallerinin geliştirilmesi ve işletilmesi konusunda uzmanlaşmıştır.' },
    subscriptionStartDate: '2025-10-22',
    subscriptionEndDate: '2025-10-24',
  },
  {
    id: 2,
    companyName: { en: 'Dof Robotic Industry Inc.', tr: 'Dof Robotik Sanayi A.Ş.' },
    ticker: 'DOFRB',
    logoUrl: 'https://picsum.photos/seed/dofrb/200',
    description: { en: 'A technology company specializing in industrial robotics and automation systems.', tr: 'Endüstriyel robotik ve otomasyon sistemleri konusunda uzmanlaşmış bir teknoloji şirketi.' },
    ipoDate: '2025-09-03',
    status: IPOStatus.COMPLETED,
    priceRange: null,
    finalPrice: 45.00,
    sharesOffered: 45000000,
    exchange: 'Yıldız Pazar',
    sector: IPOSector.INDUSTRIALS,
    distributionMethod: { en: 'Equal Distribution', tr: 'Eşit Dağıtım' },
    background: { en: 'Dof Robotic Industry Inc. designs and manufactures advanced robotic solutions for various industries, aiming to increase efficiency and productivity through automation.', tr: 'Dof Robotik Sanayi A.Ş., otomasyon yoluyla verimliliği ve üretkenliği artırmayı hedefleyerek çeşitli endüstriler için gelişmiş robotik çözümler tasarlar ve üretir.' },
    subscriptionStartDate: '2025-09-03',
    subscriptionEndDate: '2025-09-05',
  },
  {
    id: 3,
    companyName: { en: 'Damla Kent Project Real Estate Certificate', tr: 'Damla Kent Projesi Gayrimenkul Sertifikası' },
    ticker: 'DMLKT',
    logoUrl: 'https://picsum.photos/seed/dmlkt/200',
    description: { en: 'A real estate certificate for the Damla Kent residential project.', tr: 'Damla Kent konut projesi için bir gayrimenkul sertifikası.' },
    ipoDate: '2025-08-04',
    status: IPOStatus.COMPLETED,
    priceRange: null,
    finalPrice: 7.59,
    sharesOffered: 1923481733,
    exchange: 'Yapılandırılmış Ürünler ve Fon Pazarı',
    sector: IPOSector.FINANCE,
    distributionMethod: { en: 'Proportional Distribution', tr: 'Oransal Dağıtım' },
    background: { en: 'The Damla Kent Project Real Estate Certificate allows investors to participate in the financing and returns of a major urban development project.', tr: 'Damla Kent Projesi Gayrimenkul Sertifikası, yatırımcıların büyük bir kentsel gelişim projesinin finansmanına ve getirilerine katılmasına olanak tanır.' },
    subscriptionStartDate: '2025-08-04',
    subscriptionEndDate: '2025-08-08',
  },
  {
    id: 4,
    companyName: { en: 'Bulls Venture Capital Investment Trust Inc.', tr: 'Bulls Girişim Sermayesi Yatırım Ortaklığı A.Ş.' },
    ticker: 'BULGS',
    logoUrl: 'https://picsum.photos/seed/bulgs/200',
    description: { en: 'A venture capital firm investing in high-growth potential startups.', tr: 'Yüksek büyüme potansiyeline sahip startup\'lara yatırım yapan bir girişim sermayesi şirketi.' },
    ipoDate: '2025-02-14',
    status: IPOStatus.COMPLETED,
    priceRange: null,
    finalPrice: 12.18,
    sharesOffered: 72500000,
    exchange: 'Ana Pazar',
    sector: IPOSector.FINANCE,
    distributionMethod: { en: 'Equal Distribution', tr: 'Eşit Dağıtım' },
    background: { en: 'Bulls Venture Capital focuses on identifying and nurturing innovative companies, providing them with the capital and strategic support needed to scale and succeed.', tr: 'Bulls Girişim Sermayesi, yenilikçi şirketleri belirlemeye ve beslemeye odaklanarak onlara ölçeklenmeleri ve başarılı olmaları için gereken sermayeyi ve stratejik desteği sağlar.' },
    subscriptionStartDate: '2025-02-14',
    subscriptionEndDate: '2025-02-17',
  }
];
